-- =============================================================================
-- MySection — Supabase initialisation
-- =============================================================================
-- Generated by: scripts/generate-supabase-sql.mjs
-- Generated at: 2026-04-24T23:37:45.443Z
--
-- Paste this whole file into the Supabase SQL Editor and hit Run.
-- Safe to re-run: drops and recreates everything.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Clean slate (only drops MySection tables — doesn't touch auth/storage/etc)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS price_history CASCADE;
DROP TABLE IF EXISTS prices         CASCADE;
DROP TABLE IF EXISTS product_links  CASCADE;
DROP TABLE IF EXISTS product_colors CASCADE;
DROP TABLE IF EXISTS products       CASCADE;
DROP TABLE IF EXISTS brands         CASCADE;
DROP TABLE IF EXISTS retailers      CASCADE;
DROP TABLE IF EXISTS notifications  CASCADE;

-- -----------------------------------------------------------------------------
-- Schema
-- -----------------------------------------------------------------------------

CREATE TABLE brands (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  logo_key    TEXT,                      -- filename in assets/brands/
  logo_url    TEXT,                      -- optional: CDN URL
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE retailers (
  id            TEXT PRIMARY KEY,        -- slug, e.g. 'chris-and-sons'
  name          TEXT NOT NULL UNIQUE,    -- display name
  country       TEXT DEFAULT 'UK',
  base_url      TEXT,
  affiliate_net TEXT,                    -- 'amazon' | 'awin' | 'cj' | 'direct' | null
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE products (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  brand_id          TEXT REFERENCES brands(id) ON DELETE SET NULL,
  category          TEXT NOT NULL,
  base_price        NUMERIC(10,2) NOT NULL,   -- used for sorting/filtering
  image_key         TEXT,                     -- filename in assets/products/
  image_url         TEXT,                     -- optional: CDN URL
  description       TEXT,
  is_new            BOOLEAN DEFAULT FALSE,
  trending          BOOLEAN DEFAULT FALSE,
  upcoming_release  BOOLEAN DEFAULT FALSE,
  release_date      DATE,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_products_brand    ON products(brand_id);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_trending ON products(trending) WHERE trending = TRUE;
CREATE INDEX idx_products_is_new   ON products(is_new)   WHERE is_new   = TRUE;

CREATE TABLE product_colors (
  id                  BIGSERIAL PRIMARY KEY,
  product_id          TEXT REFERENCES products(id) ON DELETE CASCADE,
  name                TEXT NOT NULL,
  hex                 TEXT NOT NULL,
  image_key           TEXT,
  linked_product_id   TEXT REFERENCES products(id) ON DELETE SET NULL,
  sort_order          INT DEFAULT 0
);
CREATE INDEX idx_colors_product ON product_colors(product_id);

CREATE TABLE product_links (
  id              BIGSERIAL PRIMARY KEY,
  product_id      TEXT REFERENCES products(id) ON DELETE CASCADE,
  retailer_id     TEXT REFERENCES retailers(id) ON DELETE CASCADE,
  url             TEXT NOT NULL,         -- the retailer's product page (used by scraper)
  sku             TEXT,                  -- retailer's product ID if known
  last_scraped_at TIMESTAMPTZ,
  scrape_ok       BOOLEAN DEFAULT TRUE,
  UNIQUE (product_id, retailer_id)
);
CREATE INDEX idx_links_product  ON product_links(product_id);
CREATE INDEX idx_links_retailer ON product_links(retailer_id);

CREATE TABLE prices (
  id            BIGSERIAL PRIMARY KEY,
  product_id    TEXT REFERENCES products(id) ON DELETE CASCADE,
  retailer_id   TEXT REFERENCES retailers(id) ON DELETE CASCADE,
  price         NUMERIC(10,2) NOT NULL,
  currency      TEXT DEFAULT 'GBP',
  in_stock      BOOLEAN DEFAULT TRUE,
  url           TEXT,                    -- denormalised for fast reads
  fetched_at    TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at  TIMESTAMPTZ,             -- last successful scrape
  last_checked_at TIMESTAMPTZ,           -- last attempted scrape (success or fail)
  last_error    TEXT,                    -- error message from last failed scrape
  UNIQUE (product_id, retailer_id)       -- one current price per pair
);
CREATE INDEX idx_prices_product ON prices(product_id);

CREATE TABLE price_history (
  id            BIGSERIAL PRIMARY KEY,
  product_id    TEXT REFERENCES products(id) ON DELETE CASCADE,
  retailer_id   TEXT REFERENCES retailers(id) ON DELETE CASCADE,
  price         NUMERIC(10,2) NOT NULL,
  currency      TEXT DEFAULT 'GBP',
  in_stock      BOOLEAN DEFAULT TRUE,
  seen_at       TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_history_product_time ON price_history(product_id, seen_at DESC);

CREATE TABLE notifications (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  message         TEXT NOT NULL,
  type            TEXT NOT NULL,         -- 'release' | 'price_drop' | 'vat_free' | ...
  date            DATE NOT NULL,
  ends_at         TIMESTAMPTZ,
  retailer_id     TEXT REFERENCES retailers(id) ON DELETE SET NULL,
  discount_label  TEXT,
  urgent          BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_notifications_date ON notifications(date DESC);

-- -----------------------------------------------------------------------------
-- Row-Level Security
-- Everyone (incl. anon) can READ. Writes require the service_role key.
-- -----------------------------------------------------------------------------
ALTER TABLE brands          ENABLE ROW LEVEL SECURITY;
ALTER TABLE retailers       ENABLE ROW LEVEL SECURITY;
ALTER TABLE products        ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_colors  ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_links   ENABLE ROW LEVEL SECURITY;
ALTER TABLE prices          ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_history   ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read brands"         ON brands         FOR SELECT USING (TRUE);
CREATE POLICY "public read retailers"      ON retailers      FOR SELECT USING (TRUE);
CREATE POLICY "public read products"       ON products       FOR SELECT USING (TRUE);
CREATE POLICY "public read product_colors" ON product_colors FOR SELECT USING (TRUE);
CREATE POLICY "public read product_links"  ON product_links  FOR SELECT USING (TRUE);
CREATE POLICY "public read prices"         ON prices         FOR SELECT USING (TRUE);
CREATE POLICY "public read price_history"  ON price_history  FOR SELECT USING (TRUE);
CREATE POLICY "public read notifications"  ON notifications  FOR SELECT USING (TRUE);

-- -----------------------------------------------------------------------------
-- Seed data (from data/*.csv)
-- -----------------------------------------------------------------------------

-- Brands (9)
INSERT INTO brands (id, name, logo_key) VALUES
  ('1', 'BaByliss PRO', 'babyliss'),
  ('2', 'Wahl', 'wahl'),
  ('3', 'Andis', 'andis'),
  ('4', 'Gamma+', 'gamma-plus'),
  ('5', 'StyleCraft', 'stylecraft'),
  ('6', 'JRL', 'jrl'),
  ('7', 'Tomb45', 'tomb45'),
  ('8', 'Supreme Trimmer', 'supreme-trimmer'),
  ('9', 'Omni', 'omni');

-- Retailers (6, inferred from prices.csv)
INSERT INTO retailers (id, name, country) VALUES
  ('amazon-uk', 'Amazon UK', 'UK'),
  ('chris-sons', 'Chris & Sons', 'UK'),
  ('coolblades', 'Coolblades', 'UK'),
  ('jrl-direct', 'JRL Direct', 'UK'),
  ('salons-direct', 'Salons Direct', 'UK'),
  ('tomb45-direct', 'Tomb45 Direct', 'UK');

-- Products (41)
INSERT INTO products (id, name, brand_id, category, base_price, image_key, description, is_new, trending, upcoming_release, release_date) VALUES
  ('1', 'Skeleton FX', '1', 'Trimmers', 149.99, 'skeleton-fx', 'Lightweight skeleton-style outliner trimmer with a precision T-blade. A barber shop staple.', FALSE, TRUE, FALSE, NULL),
  ('2', 'Senior Cordless', '2', 'Clippers', 189.99, 'wahl-senior', 'Iconic Wahl Senior in a cordless build. Premium V9000 motor for serious power.', FALSE, TRUE, FALSE, NULL),
  ('3', 'GTX-Z', '3', 'Trimmers', 129.99, 'gtx-z', 'Slim zero-gapped trimmer with a deep-tooth blade. Built for sharp lines and bald fades.', FALSE, TRUE, FALSE, NULL),
  ('4', 'Boosted+ Trimmer', '4', 'Trimmers', 179.99, 'boosted', 'High-torque magnetic motor trimmer. Boosted+ delivers extra cutting power.', TRUE, FALSE, FALSE, '2026-02-01'),
  ('5', 'Saber Trimmer', '5', 'Trimmers', 159.99, 'saber', 'All-new from StyleCraft. Slim profile with the speed of a magnetic motor.', TRUE, TRUE, FALSE, '2026-04-15'),
  ('6', 'Fresh Fade 2020C', '6', 'Clippers', 229.99, 'fresh-fade-2020c', 'Pro-grade clipper from JRL. Cordless freedom with corded power.', FALSE, FALSE, FALSE, NULL),
  ('7', 'Power Clip', '7', 'Clippers', 219.99, 'power-clip', 'Tomb45 Power Clip with PowerClip wireless charging. Performance meets innovation.', TRUE, FALSE, FALSE, '2026-03-10'),
  ('8', 'Prodigy', '8', 'Trimmers', 99.99, 'prodigy', 'Affordable pro-level trimmer. The Prodigy punches above its price.', FALSE, FALSE, FALSE, NULL),
  ('9', 'Magic Clip Cordless', '2', 'Clippers', 169.99, 'magic-clip', 'The legendary 5-Star Magic Clip cordless. Stagger-tooth blade for blending and fading.', FALSE, TRUE, FALSE, NULL),
  ('10', 'Absolute Zero', '5', 'Trimmers', 189.99, 'absolute-zero', 'Zero-gapped from the factory. Premium build with a powerful motor.', FALSE, FALSE, FALSE, NULL),
  ('11', 'Fade Brush', '7', 'Brushes', 29.99, 'fade-brush', 'The original fade brush — clears hair from blades and cape. Barber essential.', FALSE, TRUE, FALSE, NULL),
  ('12', 'Gold FX Clipper', '1', 'Clippers', 229.99, 'gold-fx', 'Iconic gold finish. The FX Clipper with the looks to match the performance.', FALSE, TRUE, FALSE, NULL),
  ('13', 'Ergo Clipper', '4', 'Clippers', 179.99, 'ergo', 'Ergonomic grip designed for all-day comfort. Pro magnetic motor.', FALSE, FALSE, FALSE, NULL),
  ('14', 'Stinger Guards', '3', 'Guards', 24.99, 'stinger-guards', 'Premium guard set for the Andis Stinger. Precision sizing for accurate fades.', FALSE, FALSE, FALSE, NULL),
  ('15', 'X-Ergo Trimmer', '4', 'Trimmers', 189.99, 'x-ergo', 'The next evolution of the Ergo. Ships May 2026.', FALSE, FALSE, TRUE, '2026-05-01'),
  ('16', 'FF2020T Trimmer', '6', 'Trimmers', 209.99, 'ff2020t', 'JRL''s upcoming FF2020T trimmer. Pre-order info coming soon.', FALSE, FALSE, TRUE, '2026-06-15'),
  ('17', 'Blade Ice', '3', 'Blades', 14.99, 'blade-ice', 'Coolant spray for clipper and trimmer blades. Keep your tools running cool.', FALSE, FALSE, FALSE, NULL),
  ('18', 'Pro Cape', '1', 'Capes & Aprons', 39.99, 'cape', 'Lightweight pro cape. Hair-resistant fabric, fits any chair.', FALSE, FALSE, FALSE, NULL),
  ('19', 'JRL x Lamborghini Diamante Kit (Black)', '6', 'Clippers', 999, 'jrl-lamborghini-black', 'Limited edition JRL x Lamborghini collaboration. Includes the Diamante clipper and trimmer with a diamond-cut black finish and premium presentation case. Signature drop for the serious collector.', TRUE, TRUE, FALSE, NULL),
  ('20', 'JRL Onyx Cordless Clipper', '6', 'Clippers', 259, 'jrl-onyx', 'JRL''s matte black Onyx edition cordless clipper. Premium build with the proven Fresh Fade motor.', TRUE, TRUE, FALSE, NULL),
  ('21', 'Wahl 5-Star Vapor Cordless Clipper', '2', 'Clippers', 179, 'wahl-vapor', 'Chrome-finished Wahl 5-Star Vapor with signature cordless power. A head-turner on the barber station.', TRUE, FALSE, FALSE, NULL),
  ('22', 'Gamma+ Boosted Up Modular Super Torque Clipper', '4', 'Clippers', 269, 'gamma-boosted-up', 'Gamma+''s flagship Boosted Up — modular design with interchangeable lids and super-torque motor.', TRUE, TRUE, FALSE, NULL),
  ('23', 'JRL Ghost Clipper Trimmer & Foil Shaver Kit', '6', 'Clippers', 599, 'jrl-ghost-kit', 'Complete 3-piece JRL Ghost kit — cordless clipper, trimmer and foil shaver in translucent white. Pro kit in a box.', TRUE, TRUE, FALSE, NULL),
  ('24', 'Wahl Magic Clip Cordless (Black)', '2', 'Clippers', 159, 'magic-clip-black', 'The legendary 5-Star Magic Clip in a full black finish. Stagger-tooth blade, cordless freedom.', FALSE, TRUE, FALSE, NULL),
  ('25', 'JRL Ghost Cordless Clipper', '6', 'Clippers', 279, 'jrl-ghost', 'JRL Ghost Professional cordless clipper in translucent white. Pro power with a unique aesthetic.', TRUE, TRUE, FALSE, NULL),
  ('26', 'BaByliss PRO Super Motor Skeleton FX Trimmer', '1', 'Trimmers', 169, 'babyliss-super-skeleton', 'Super motor upgrade to the Skeleton FX. More torque, more cutting power, same skeleton silhouette.', TRUE, FALSE, FALSE, NULL),
  ('27', 'Wahl Hi-Viz Trimmer', '2', 'Trimmers', 89, 'wahl-hi-viz', 'High-visibility orange Wahl trimmer. Fun colour, serious precision outlining.', FALSE, FALSE, FALSE, NULL),
  ('28', 'StyleCraft Pro Brushless Saber Trimmer (Black)', '5', 'Trimmers', 179, 'saber-trimmer-black', 'Brushless motor Saber trimmer in all-black. Longer battery life and quieter operation than the standard Saber.', TRUE, TRUE, FALSE, NULL),
  ('29', 'Omni Arcane Clipper', '9', 'Clippers', 259, 'omni-arcane', 'Omni''s Arcane clipper — stealth look with modern cordless performance. Cult favourite among forward-thinking barbers.', TRUE, TRUE, FALSE, NULL),
  ('30', 'StyleCraft Instinct Clipper', '5', 'Clippers', 239, 'instinct', 'StyleCraft Instinct — a next-gen cordless clipper with precision blade and pro-grade runtime.', FALSE, TRUE, FALSE, NULL),
  ('31', 'Gamma+ Boosted Clipper', '4', 'Clippers', 219, 'gamma-boosted', 'The original Gamma+ Boosted clipper — super-torque magnetic motor at a barber-friendly price.', FALSE, TRUE, FALSE, NULL),
  ('32', 'Wahl Senior 2.0 Cordless Clipper', '2', 'Clippers', 219, 'wahl-senior-2', 'The updated Wahl Senior 2.0 cordless. Stronger motor, longer runtime — the iconic Senior reimagined.', TRUE, TRUE, FALSE, NULL),
  ('33', 'BaByliss PRO Cordless Super Motor Collection', '1', 'Clippers', 549, 'babyliss-super-collection', 'The full BaByliss PRO Super Motor collection — clipper, trimmer and skeleton in one premium bundle.', TRUE, FALSE, FALSE, NULL),
  ('34', 'Gamma+ Boosted Super Torque Motor Trimmer', '4', 'Trimmers', 179, 'gamma-boosted-trimmer', 'Trimmer sibling to the Boosted clipper. Super-torque motor for effortless detail work.', FALSE, TRUE, FALSE, NULL),
  ('35', 'Wahl Magic Clip Cordless (Gold)', '2', 'Clippers', 169, 'magic-clip-gold', 'The iconic Magic Clip dressed in gold. Same legendary performance, premium gold finish.', FALSE, FALSE, FALSE, NULL),
  ('36', 'StyleCraft Saber 2.0 Brushless Clipper (Black)', '5', 'Clippers', 239, 'saber-2-black', 'StyleCraft Saber 2.0 — brushless motor clipper in black. The successor to the popular original.', TRUE, TRUE, FALSE, NULL),
  ('37', 'StyleCraft Pro Brushless Saber Trimmer (White)', '5', 'Trimmers', 179, 'saber-trimmer-white', 'Brushless motor Saber trimmer in clean white finish. Matches the Saber 2.0 clipper perfectly.', TRUE, FALSE, FALSE, NULL),
  ('38', 'BaByliss PRO Boost+ Chameleon Skeleton FX Trimmer', '1', 'Trimmers', 189, 'babyliss-chameleon', 'Boost+ Chameleon edition Skeleton FX. Colour-shift finish on the beloved skeleton trimmer body.', TRUE, TRUE, FALSE, NULL),
  ('39', 'StyleCraft Pro Metal Edition Instinct Clipper', '5', 'Clippers', 279, 'instinct-metal', 'Instinct clipper in full metal body. Weightier feel, premium look, same cordless performance.', TRUE, FALSE, FALSE, NULL),
  ('40', 'Omni Arcane Anomaly Clipper & Trimmer Combo', '9', 'Clippers', 479, 'omni-anomaly', 'Omni''s Arcane Anomaly set — matching clipper and trimmer in a presentation box.', TRUE, TRUE, FALSE, NULL),
  ('41', 'StyleCraft Rebel Clipper', '5', 'Clippers', 189, 'stylecraft-rebel', 'StyleCraft Rebel — a punchy mid-range clipper built for high-volume barbershops.', FALSE, TRUE, FALSE, NULL);

-- Product colours (10)
INSERT INTO product_colors (product_id, name, hex, image_key, linked_product_id, sort_order) VALUES
  ('1', 'Black', '#1A1A1A', 'skeleton-fx', NULL, 0),
  ('1', 'Rose Gold', '#E0BFB8', 'gold-fx', NULL, 1),
  ('1', 'Chrome', '#C0C0C0', 'skeleton-fx', NULL, 2),
  ('2', 'Black', '#1A1A1A', 'wahl-senior', NULL, 3),
  ('2', 'Chrome', '#C0C0C0', 'wahl-senior', NULL, 4),
  ('4', 'Black', '#1A1A1A', 'boosted', NULL, 5),
  ('4', 'Gold', '#D4AF37', 'gold-fx', NULL, 6),
  ('12', 'Gold', '#D4AF37', 'gold-fx', NULL, 7),
  ('12', 'Rose Gold', '#E0BFB8', 'gold-fx', NULL, 8),
  ('12', 'Black', '#1A1A1A', 'skeleton-fx', NULL, 9);

-- Product links — where each retailer sells each product (67)
INSERT INTO product_links (product_id, retailer_id, url) VALUES
  ('1', 'salons-direct', 'https://www.salonsdirect.com/products/babyliss-pro-snap-fx-skeleton-dlc-blade'),
  ('1', 'coolblades', 'https://www.coolblades.co.uk/babyliss-pro-super-motor-skeleton-trimmer/'),
  ('1', 'chris-sons', 'https://chrisandsons.co.uk/skeleton-fx'),
  ('1', 'amazon-uk', 'https://amazon.co.uk/dp/skeleton-fx'),
  ('2', 'salons-direct', 'https://www.salonsdirect.com/products/wahl-5-star-cordless-senior-hair-clipper-kit'),
  ('2', 'coolblades', 'https://www.coolblades.co.uk/wahl-senior-2-0-cordless-clipper/'),
  ('2', 'amazon-uk', 'https://amazon.co.uk/dp/wahl-senior'),
  ('2', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-cordless-senior-clipper.html'),
  ('3', 'salons-direct', 'https://salonsdirect.com/gtx-z'),
  ('3', 'coolblades', 'https://www.coolblades.co.uk/andis-gtx-exo-cordless-trimmer/'),
  ('3', 'chris-sons', 'https://chrisandsons.co.uk/gtx-z'),
  ('4', 'coolblades', 'https://www.coolblades.co.uk/gamma-boosted-trimmer/'),
  ('4', 'amazon-uk', 'https://amazon.co.uk/dp/boosted'),
  ('5', 'coolblades', 'https://www.coolblades.co.uk/stylecraft-saber-clipper/'),
  ('5', 'salons-direct', 'https://salonsdirect.com/saber'),
  ('5', 'chris-sons', 'https://chrisandsons.co.uk/saber'),
  ('6', 'salons-direct', 'https://salonsdirect.com/jrl-fresh-fade'),
  ('6', 'coolblades', 'https://www.coolblades.co.uk/jrl-fresh-fade-2020c-clipper/'),
  ('6', 'chris-sons', 'https://www.chrisandsons.co.uk/jrl-freshfade-2020c-clipper.html'),
  ('7', 'coolblades', 'https://coolblades.co.uk/tomb45-power-clip'),
  ('7', 'amazon-uk', 'https://amazon.co.uk/dp/tomb45-power-clip'),
  ('8', 'amazon-uk', 'https://amazon.co.uk/dp/supreme-prodigy'),
  ('8', 'coolblades', 'https://coolblades.co.uk/supreme-prodigy'),
  ('9', 'salons-direct', 'https://www.salonsdirect.com/products/wahl-5-star-magic-clip-cordless-hair-clipper-kit'),
  ('9', 'coolblades', 'https://www.coolblades.co.uk/wahl-cordless-magic-clip-clipper/'),
  ('9', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-cordless-magic-clipper.html'),
  ('9', 'amazon-uk', 'https://amazon.co.uk/dp/magic-clip'),
  ('10', 'salons-direct', 'https://salonsdirect.com/absolute-zero'),
  ('10', 'coolblades', 'https://coolblades.co.uk/absolute-zero'),
  ('11', 'tomb45-direct', 'https://tomb45.com/fade-brush'),
  ('11', 'amazon-uk', 'https://amazon.co.uk/dp/tomb45-fade-brush'),
  ('12', 'salons-direct', 'https://salonsdirect.com/gold-fx'),
  ('12', 'coolblades', NULL),
  ('12', 'chris-sons', 'https://chrisandsons.co.uk/gold-fx'),
  ('13', 'coolblades', 'https://www.coolblades.co.uk/gamma-x-ergo-clipper/'),
  ('14', 'amazon-uk', 'https://amazon.co.uk/dp/stinger-guards'),
  ('14', 'salons-direct', 'https://salonsdirect.com/stinger-guards'),
  ('17', 'amazon-uk', 'https://amazon.co.uk/dp/andis-blade-ice'),
  ('17', 'salons-direct', 'https://salonsdirect.com/andis-blade-ice'),
  ('18', 'salons-direct', 'https://salonsdirect.com/babyliss-cape'),
  ('18', 'coolblades', 'https://coolblades.co.uk/babyliss-cape'),
  ('19', 'jrl-direct', 'https://jrlusa.com/lamborghini-diamante'),
  ('19', 'salons-direct', 'https://salonsdirect.com/jrl-lamborghini-diamante'),
  ('19', 'coolblades', 'https://www.coolblades.co.uk/jrl-x-lamborghini-diamante-clipper-trimmer-kit/'),
  ('19', 'chris-sons', 'https://www.chrisandsons.co.uk/jrl-x-lamborghini-clipper-trimmer-kit-black.html'),
  ('20', 'chris-sons', 'https://www.chrisandsons.co.uk/jrl-onyx-professional-cordless-hair-clipper.html'),
  ('21', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-5-star-vapor-cordless-clipper.html'),
  ('22', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-boosted-up-modular-super-torque-clipper.html'),
  ('23', 'chris-sons', 'https://www.chrisandsons.co.uk/jrl-ghost-clipper-trimmer-and-foil-shaver.html'),
  ('24', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-black-cordless-magic-clip-clipper.html'),
  ('25', 'chris-sons', 'https://www.chrisandsons.co.uk/jrl-ghost-professional-cordless-hair-clipper.html'),
  ('26', 'chris-sons', 'https://www.chrisandsons.co.uk/babyliss-super-motor-skeleton-trimmer.html'),
  ('27', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-hi-viz-trimmer.html'),
  ('28', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-black.html'),
  ('29', 'chris-sons', 'https://www.chrisandsons.co.uk/omni-arcane-hair-clipper.html'),
  ('30', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-instinct-clipper.html'),
  ('31', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-boosted-clipper.html'),
  ('32', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-senior-2-0-cordless-clipper.html'),
  ('33', 'chris-sons', 'https://www.chrisandsons.co.uk/babyliss-pro-cordless-super-motor-collection.html'),
  ('34', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-boosted-super-torque-motor-trimmer.html'),
  ('35', 'chris-sons', 'https://www.chrisandsons.co.uk/wahl-gold-cordless-magic-clip.html'),
  ('36', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-saber-2-0-brushless-motor-clipper-black.html'),
  ('37', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-white.html'),
  ('38', 'chris-sons', 'https://www.chrisandsons.co.uk/babyliss-pro-boost-chameleon-skeleton-fx-trimmer.html'),
  ('39', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-metal-edition-instinct-clipper.html'),
  ('40', 'chris-sons', 'https://www.chrisandsons.co.uk/omni-arcane-anomaly-clipper-and-trimmer-combo.html'),
  ('41', 'chris-sons', 'https://www.chrisandsons.co.uk/gamma-stylecraft-rebel-clipper.html')
ON CONFLICT (product_id, retailer_id) DO UPDATE SET url = EXCLUDED.url;

-- Current prices (67)
INSERT INTO prices (product_id, retailer_id, price, in_stock, url) VALUES
  ('1', 'salons-direct', 144.99, TRUE, 'https://www.salonsdirect.com/products/babyliss-pro-snap-fx-skeleton-dlc-blade'),
  ('1', 'coolblades', 149.99, TRUE, 'https://www.coolblades.co.uk/babyliss-pro-super-motor-skeleton-trimmer/'),
  ('1', 'chris-sons', 142.5, TRUE, 'https://chrisandsons.co.uk/skeleton-fx'),
  ('1', 'amazon-uk', 154, TRUE, 'https://amazon.co.uk/dp/skeleton-fx'),
  ('2', 'salons-direct', 184.99, TRUE, 'https://www.salonsdirect.com/products/wahl-5-star-cordless-senior-hair-clipper-kit'),
  ('2', 'coolblades', 189.99, TRUE, 'https://www.coolblades.co.uk/wahl-senior-2-0-cordless-clipper/'),
  ('2', 'amazon-uk', 194.99, TRUE, 'https://amazon.co.uk/dp/wahl-senior'),
  ('2', 'chris-sons', 189, TRUE, 'https://www.chrisandsons.co.uk/wahl-cordless-senior-clipper.html'),
  ('3', 'salons-direct', 124.99, TRUE, 'https://salonsdirect.com/gtx-z'),
  ('3', 'coolblades', 129.99, FALSE, 'https://www.coolblades.co.uk/andis-gtx-exo-cordless-trimmer/'),
  ('3', 'chris-sons', 127, TRUE, 'https://chrisandsons.co.uk/gtx-z'),
  ('4', 'coolblades', 179.99, TRUE, 'https://www.coolblades.co.uk/gamma-boosted-trimmer/'),
  ('4', 'amazon-uk', 184.99, TRUE, 'https://amazon.co.uk/dp/boosted'),
  ('5', 'coolblades', 159.99, TRUE, 'https://www.coolblades.co.uk/stylecraft-saber-clipper/'),
  ('5', 'salons-direct', 154.99, TRUE, 'https://salonsdirect.com/saber'),
  ('5', 'chris-sons', 159.99, TRUE, 'https://chrisandsons.co.uk/saber'),
  ('6', 'salons-direct', 224.99, TRUE, 'https://salonsdirect.com/jrl-fresh-fade'),
  ('6', 'coolblades', 229.99, TRUE, 'https://www.coolblades.co.uk/jrl-fresh-fade-2020c-clipper/'),
  ('6', 'chris-sons', 219, TRUE, 'https://www.chrisandsons.co.uk/jrl-freshfade-2020c-clipper.html'),
  ('7', 'coolblades', 219.99, TRUE, 'https://coolblades.co.uk/tomb45-power-clip'),
  ('7', 'amazon-uk', 224.99, FALSE, 'https://amazon.co.uk/dp/tomb45-power-clip'),
  ('8', 'amazon-uk', 99.99, TRUE, 'https://amazon.co.uk/dp/supreme-prodigy'),
  ('8', 'coolblades', 99.99, TRUE, 'https://coolblades.co.uk/supreme-prodigy'),
  ('9', 'salons-direct', 164.99, TRUE, 'https://www.salonsdirect.com/products/wahl-5-star-magic-clip-cordless-hair-clipper-kit'),
  ('9', 'coolblades', 169.99, TRUE, 'https://www.coolblades.co.uk/wahl-cordless-magic-clip-clipper/'),
  ('9', 'chris-sons', 162.5, TRUE, 'https://www.chrisandsons.co.uk/wahl-cordless-magic-clipper.html'),
  ('9', 'amazon-uk', 174.99, TRUE, 'https://amazon.co.uk/dp/magic-clip'),
  ('10', 'salons-direct', 184.99, TRUE, 'https://salonsdirect.com/absolute-zero'),
  ('10', 'coolblades', 189.99, TRUE, 'https://coolblades.co.uk/absolute-zero'),
  ('11', 'tomb45-direct', 29.99, TRUE, 'https://tomb45.com/fade-brush'),
  ('11', 'amazon-uk', 32.99, TRUE, 'https://amazon.co.uk/dp/tomb45-fade-brush'),
  ('12', 'salons-direct', 224.99, TRUE, 'https://salonsdirect.com/gold-fx'),
  ('12', 'coolblades', 229.99, TRUE, NULL),
  ('12', 'chris-sons', 222, TRUE, 'https://chrisandsons.co.uk/gold-fx'),
  ('13', 'coolblades', 179.99, TRUE, 'https://www.coolblades.co.uk/gamma-x-ergo-clipper/'),
  ('14', 'amazon-uk', 24.99, TRUE, 'https://amazon.co.uk/dp/stinger-guards'),
  ('14', 'salons-direct', 22.99, TRUE, 'https://salonsdirect.com/stinger-guards'),
  ('17', 'amazon-uk', 14.99, TRUE, 'https://amazon.co.uk/dp/andis-blade-ice'),
  ('17', 'salons-direct', 12.99, TRUE, 'https://salonsdirect.com/andis-blade-ice'),
  ('18', 'salons-direct', 39.99, TRUE, 'https://salonsdirect.com/babyliss-cape'),
  ('18', 'coolblades', 42.99, TRUE, 'https://coolblades.co.uk/babyliss-cape'),
  ('19', 'jrl-direct', 999, TRUE, 'https://jrlusa.com/lamborghini-diamante'),
  ('19', 'salons-direct', 949.99, TRUE, 'https://salonsdirect.com/jrl-lamborghini-diamante'),
  ('19', 'coolblades', 979.99, FALSE, 'https://www.coolblades.co.uk/jrl-x-lamborghini-diamante-clipper-trimmer-kit/'),
  ('19', 'chris-sons', 959, TRUE, 'https://www.chrisandsons.co.uk/jrl-x-lamborghini-clipper-trimmer-kit-black.html'),
  ('20', 'chris-sons', 259, TRUE, 'https://www.chrisandsons.co.uk/jrl-onyx-professional-cordless-hair-clipper.html'),
  ('21', 'chris-sons', 179, TRUE, 'https://www.chrisandsons.co.uk/wahl-5-star-vapor-cordless-clipper.html'),
  ('22', 'chris-sons', 269, TRUE, 'https://www.chrisandsons.co.uk/gamma-boosted-up-modular-super-torque-clipper.html'),
  ('23', 'chris-sons', 599, TRUE, 'https://www.chrisandsons.co.uk/jrl-ghost-clipper-trimmer-and-foil-shaver.html'),
  ('24', 'chris-sons', 159, TRUE, 'https://www.chrisandsons.co.uk/wahl-black-cordless-magic-clip-clipper.html'),
  ('25', 'chris-sons', 279, TRUE, 'https://www.chrisandsons.co.uk/jrl-ghost-professional-cordless-hair-clipper.html'),
  ('26', 'chris-sons', 169, TRUE, 'https://www.chrisandsons.co.uk/babyliss-super-motor-skeleton-trimmer.html'),
  ('27', 'chris-sons', 89, TRUE, 'https://www.chrisandsons.co.uk/wahl-hi-viz-trimmer.html'),
  ('28', 'chris-sons', 179, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-black.html'),
  ('29', 'chris-sons', 259, TRUE, 'https://www.chrisandsons.co.uk/omni-arcane-hair-clipper.html'),
  ('30', 'chris-sons', 239, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-instinct-clipper.html'),
  ('31', 'chris-sons', 219, TRUE, 'https://www.chrisandsons.co.uk/gamma-boosted-clipper.html'),
  ('32', 'chris-sons', 219, TRUE, 'https://www.chrisandsons.co.uk/wahl-senior-2-0-cordless-clipper.html'),
  ('33', 'chris-sons', 549, TRUE, 'https://www.chrisandsons.co.uk/babyliss-pro-cordless-super-motor-collection.html'),
  ('34', 'chris-sons', 179, TRUE, 'https://www.chrisandsons.co.uk/gamma-boosted-super-torque-motor-trimmer.html'),
  ('35', 'chris-sons', 169, TRUE, 'https://www.chrisandsons.co.uk/wahl-gold-cordless-magic-clip.html'),
  ('36', 'chris-sons', 239, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-saber-2-0-brushless-motor-clipper-black.html'),
  ('37', 'chris-sons', 179, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-white.html'),
  ('38', 'chris-sons', 189, TRUE, 'https://www.chrisandsons.co.uk/babyliss-pro-boost-chameleon-skeleton-fx-trimmer.html'),
  ('39', 'chris-sons', 279, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-pro-metal-edition-instinct-clipper.html'),
  ('40', 'chris-sons', 479, TRUE, 'https://www.chrisandsons.co.uk/omni-arcane-anomaly-clipper-and-trimmer-combo.html'),
  ('41', 'chris-sons', 189, TRUE, 'https://www.chrisandsons.co.uk/gamma-stylecraft-rebel-clipper.html')
ON CONFLICT (product_id, retailer_id) DO UPDATE SET
  price = EXCLUDED.price,
  in_stock = EXCLUDED.in_stock,
  url = EXCLUDED.url,
  fetched_at = NOW();

-- =============================================================================
-- Done. Verify in the Supabase dashboard:
--   Table Editor → brands (9), products (41), prices (67)
-- =============================================================================
