// AUTO-GENERATED by scripts/build-data.mjs — DO NOT EDIT BY HAND.
// Edit data/*.csv files instead, then run: npm run sync-data
//
// Generated at: 2026-04-24T23:37:45.352Z
// Source: data/products.csv, data/prices.csv, data/colors.csv, data/brands.csv

import { ImageSourcePropType } from 'react-native';
import type { Product, Brand, ColorVariant } from './MockData';

// Exported so other modules (e.g. lib/DataContext.tsx) can attach the right
// bundled image to live data fetched from Supabase.
export const productImages: Record<string, ImageSourcePropType> = {
  'absolute-zero': require('../assets/products/absolute-zero.png'),
  'babyliss-chameleon': require('../assets/products/absolute-zero.png'),
  'babyliss-super-collection': require('../assets/products/absolute-zero.png'),
  'babyliss-super-skeleton': require('../assets/products/absolute-zero.png'),
  'blade-ice': require('../assets/products/blade-ice.png'),
  'boosted': require('../assets/products/boosted.png'),
  'cape': require('../assets/products/cape.png'),
  'ergo': require('../assets/products/ergo.png'),
  'fade-brush': require('../assets/products/fade-brush.png'),
  'ff2020t': require('../assets/products/ff2020t.png'),
  'fresh-fade-2020c': require('../assets/products/fresh-fade-2020c.png'),
  'gamma-boosted': require('../assets/products/absolute-zero.png'),
  'gamma-boosted-trimmer': require('../assets/products/absolute-zero.png'),
  'gamma-boosted-up': require('../assets/products/absolute-zero.png'),
  'gold-fx': require('../assets/products/gold-fx.png'),
  'gtx-z': require('../assets/products/gtx-z.png'),
  'instinct': require('../assets/products/absolute-zero.png'),
  'instinct-metal': require('../assets/products/absolute-zero.png'),
  'jrl-ghost': require('../assets/products/absolute-zero.png'),
  'jrl-ghost-kit': require('../assets/products/absolute-zero.png'),
  'jrl-lamborghini-black': require('../assets/products/absolute-zero.png'),
  'jrl-onyx': require('../assets/products/absolute-zero.png'),
  'magic-clip': require('../assets/products/magic-clip.png'),
  'magic-clip-black': require('../assets/products/absolute-zero.png'),
  'magic-clip-gold': require('../assets/products/absolute-zero.png'),
  'omni-anomaly': require('../assets/products/absolute-zero.png'),
  'omni-arcane': require('../assets/products/absolute-zero.png'),
  'power-clip': require('../assets/products/power-clip.png'),
  'prodigy': require('../assets/products/prodigy.png'),
  'saber': require('../assets/products/saber.png'),
  'saber-2-black': require('../assets/products/absolute-zero.png'),
  'saber-trimmer-black': require('../assets/products/absolute-zero.png'),
  'saber-trimmer-white': require('../assets/products/absolute-zero.png'),
  'skeleton-fx': require('../assets/products/skeleton-fx.png'),
  'stinger-guards': require('../assets/products/stinger-guards.png'),
  'stylecraft-rebel': require('../assets/products/absolute-zero.png'),
  'wahl-hi-viz': require('../assets/products/absolute-zero.png'),
  'wahl-senior': require('../assets/products/wahl-senior.png'),
  'wahl-senior-2': require('../assets/products/absolute-zero.png'),
  'wahl-vapor': require('../assets/products/absolute-zero.png'),
  'x-ergo': require('../assets/products/x-ergo.png'),
};

export const brandLogos: Record<string, ImageSourcePropType> = {
  'babyliss': require('../assets/brands/babyliss.png'),
  'wahl': require('../assets/brands/wahl.png'),
  'andis': require('../assets/brands/andis.png'),
  'gamma-plus': require('../assets/brands/gamma-plus.png'),
  'stylecraft': require('../assets/brands/stylecraft.png'),
  'jrl': require('../assets/brands/jrl.png'),
  'tomb45': require('../assets/brands/tomb45.png'),
  'supreme-trimmer': require('../assets/brands/supreme-trimmer.png'),
  'omni': require('../assets/brands/andis.png'),
};

export const generatedBrands: Brand[] = [
  {
    "id": "1",
    "name": "BaByliss PRO",
    "logo": brandLogos['babyliss']
  },
  {
    "id": "2",
    "name": "Wahl",
    "logo": brandLogos['wahl']
  },
  {
    "id": "3",
    "name": "Andis",
    "logo": brandLogos['andis']
  },
  {
    "id": "4",
    "name": "Gamma+",
    "logo": brandLogos['gamma-plus']
  },
  {
    "id": "5",
    "name": "StyleCraft",
    "logo": brandLogos['stylecraft']
  },
  {
    "id": "6",
    "name": "JRL",
    "logo": brandLogos['jrl']
  },
  {
    "id": "7",
    "name": "Tomb45",
    "logo": brandLogos['tomb45']
  },
  {
    "id": "8",
    "name": "Supreme Trimmer",
    "logo": brandLogos['supreme-trimmer']
  },
  {
    "id": "9",
    "name": "Omni",
    "logo": brandLogos['omni']
  }
];

export const generatedProducts: Product[] = [
  {
    "id": "1",
    "name": "Skeleton FX",
    "brand": "BaByliss PRO",
    "category": "Trimmers",
    "price": 149.99,
    "image": productImages['skeleton-fx'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://www.salonsdirect.com/products/babyliss-pro-snap-fx-skeleton-dlc-blade",
        "inStock": true,
        "price": 144.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/babyliss-pro-super-motor-skeleton-trimmer/",
        "inStock": true,
        "price": 149.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://chrisandsons.co.uk/skeleton-fx",
        "inStock": true,
        "price": 142.5
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/skeleton-fx",
        "inStock": true,
        "price": 154
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "Lightweight skeleton-style outliner trimmer with a precision T-blade. A barber shop staple.",
    "colors": [
      {
        "name": "Black",
        "hex": "#1A1A1A",
        "image": productImages['skeleton-fx']
      },
      {
        "name": "Rose Gold",
        "hex": "#E0BFB8",
        "image": productImages['gold-fx']
      },
      {
        "name": "Chrome",
        "hex": "#C0C0C0",
        "image": productImages['skeleton-fx']
      }
    ]
  },
  {
    "id": "2",
    "name": "Senior Cordless",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 189.99,
    "image": productImages['wahl-senior'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://www.salonsdirect.com/products/wahl-5-star-cordless-senior-hair-clipper-kit",
        "inStock": true,
        "price": 184.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/wahl-senior-2-0-cordless-clipper/",
        "inStock": true,
        "price": 189.99
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/wahl-senior",
        "inStock": true,
        "price": 194.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-cordless-senior-clipper.html",
        "inStock": true,
        "price": 189
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "Iconic Wahl Senior in a cordless build. Premium V9000 motor for serious power.",
    "colors": [
      {
        "name": "Black",
        "hex": "#1A1A1A",
        "image": productImages['wahl-senior']
      },
      {
        "name": "Chrome",
        "hex": "#C0C0C0",
        "image": productImages['wahl-senior']
      }
    ]
  },
  {
    "id": "3",
    "name": "GTX-Z",
    "brand": "Andis",
    "category": "Trimmers",
    "price": 129.99,
    "image": productImages['gtx-z'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/gtx-z",
        "inStock": true,
        "price": 124.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/andis-gtx-exo-cordless-trimmer/",
        "inStock": true,
        "price": 129.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://chrisandsons.co.uk/gtx-z",
        "inStock": true,
        "price": 127
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "Slim zero-gapped trimmer with a deep-tooth blade. Built for sharp lines and bald fades."
  },
  {
    "id": "4",
    "name": "Boosted+ Trimmer",
    "brand": "Gamma+",
    "category": "Trimmers",
    "price": 179.99,
    "image": productImages['boosted'],
    "stores": [
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/gamma-boosted-trimmer/",
        "inStock": true,
        "price": 179.99
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/boosted",
        "inStock": true,
        "price": 184.99
      }
    ],
    "trending": false,
    "isNew": true,
    "releaseDate": "2026-02-01",
    "description": "High-torque magnetic motor trimmer. Boosted+ delivers extra cutting power.",
    "colors": [
      {
        "name": "Black",
        "hex": "#1A1A1A",
        "image": productImages['boosted']
      },
      {
        "name": "Gold",
        "hex": "#D4AF37",
        "image": productImages['gold-fx']
      }
    ]
  },
  {
    "id": "5",
    "name": "Saber Trimmer",
    "brand": "StyleCraft",
    "category": "Trimmers",
    "price": 159.99,
    "image": productImages['saber'],
    "stores": [
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/stylecraft-saber-clipper/",
        "inStock": true,
        "price": 159.99
      },
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/saber",
        "inStock": true,
        "price": 154.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://chrisandsons.co.uk/saber",
        "inStock": true,
        "price": 159.99
      }
    ],
    "trending": true,
    "isNew": true,
    "releaseDate": "2026-04-15",
    "description": "All-new from StyleCraft. Slim profile with the speed of a magnetic motor."
  },
  {
    "id": "6",
    "name": "Fresh Fade 2020C",
    "brand": "JRL",
    "category": "Clippers",
    "price": 229.99,
    "image": productImages['fresh-fade-2020c'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/jrl-fresh-fade",
        "inStock": true,
        "price": 224.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/jrl-fresh-fade-2020c-clipper/",
        "inStock": true,
        "price": 229.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/jrl-freshfade-2020c-clipper.html",
        "inStock": true,
        "price": 219
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Pro-grade clipper from JRL. Cordless freedom with corded power."
  },
  {
    "id": "7",
    "name": "Power Clip",
    "brand": "Tomb45",
    "category": "Clippers",
    "price": 219.99,
    "image": productImages['power-clip'],
    "stores": [
      {
        "name": "Coolblades",
        "url": "https://coolblades.co.uk/tomb45-power-clip",
        "inStock": true,
        "price": 219.99
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/tomb45-power-clip",
        "inStock": true,
        "price": 224.99
      }
    ],
    "trending": false,
    "isNew": true,
    "releaseDate": "2026-03-10",
    "description": "Tomb45 Power Clip with PowerClip wireless charging. Performance meets innovation."
  },
  {
    "id": "8",
    "name": "Prodigy",
    "brand": "Supreme Trimmer",
    "category": "Trimmers",
    "price": 99.99,
    "image": productImages['prodigy'],
    "stores": [
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/supreme-prodigy",
        "inStock": true,
        "price": 99.99
      },
      {
        "name": "Coolblades",
        "url": "https://coolblades.co.uk/supreme-prodigy",
        "inStock": true,
        "price": 99.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Affordable pro-level trimmer. The Prodigy punches above its price."
  },
  {
    "id": "9",
    "name": "Magic Clip Cordless",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 169.99,
    "image": productImages['magic-clip'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://www.salonsdirect.com/products/wahl-5-star-magic-clip-cordless-hair-clipper-kit",
        "inStock": true,
        "price": 164.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/wahl-cordless-magic-clip-clipper/",
        "inStock": true,
        "price": 169.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-cordless-magic-clipper.html",
        "inStock": true,
        "price": 162.5
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/magic-clip",
        "inStock": true,
        "price": 174.99
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "The legendary 5-Star Magic Clip cordless. Stagger-tooth blade for blending and fading."
  },
  {
    "id": "10",
    "name": "Absolute Zero",
    "brand": "StyleCraft",
    "category": "Trimmers",
    "price": 189.99,
    "image": productImages['absolute-zero'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/absolute-zero",
        "inStock": true,
        "price": 184.99
      },
      {
        "name": "Coolblades",
        "url": "https://coolblades.co.uk/absolute-zero",
        "inStock": true,
        "price": 189.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Zero-gapped from the factory. Premium build with a powerful motor."
  },
  {
    "id": "11",
    "name": "Fade Brush",
    "brand": "Tomb45",
    "category": "Brushes",
    "price": 29.99,
    "image": productImages['fade-brush'],
    "stores": [
      {
        "name": "Tomb45 Direct",
        "url": "https://tomb45.com/fade-brush",
        "inStock": true,
        "price": 29.99
      },
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/tomb45-fade-brush",
        "inStock": true,
        "price": 32.99
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "The original fade brush — clears hair from blades and cape. Barber essential."
  },
  {
    "id": "12",
    "name": "Gold FX Clipper",
    "brand": "BaByliss PRO",
    "category": "Clippers",
    "price": 229.99,
    "image": productImages['gold-fx'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/gold-fx",
        "inStock": true,
        "price": 224.99
      },
      {
        "name": "Coolblades",
        "url": "",
        "inStock": true,
        "price": 229.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://chrisandsons.co.uk/gold-fx",
        "inStock": true,
        "price": 222
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "Iconic gold finish. The FX Clipper with the looks to match the performance.",
    "colors": [
      {
        "name": "Gold",
        "hex": "#D4AF37",
        "image": productImages['gold-fx']
      },
      {
        "name": "Rose Gold",
        "hex": "#E0BFB8",
        "image": productImages['gold-fx']
      },
      {
        "name": "Black",
        "hex": "#1A1A1A",
        "image": productImages['skeleton-fx']
      }
    ]
  },
  {
    "id": "13",
    "name": "Ergo Clipper",
    "brand": "Gamma+",
    "category": "Clippers",
    "price": 179.99,
    "image": productImages['ergo'],
    "stores": [
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/gamma-x-ergo-clipper/",
        "inStock": true,
        "price": 179.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Ergonomic grip designed for all-day comfort. Pro magnetic motor."
  },
  {
    "id": "14",
    "name": "Stinger Guards",
    "brand": "Andis",
    "category": "Guards",
    "price": 24.99,
    "image": productImages['stinger-guards'],
    "stores": [
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/stinger-guards",
        "inStock": true,
        "price": 24.99
      },
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/stinger-guards",
        "inStock": true,
        "price": 22.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Premium guard set for the Andis Stinger. Precision sizing for accurate fades."
  },
  {
    "id": "15",
    "name": "X-Ergo Trimmer",
    "brand": "Gamma+",
    "category": "Trimmers",
    "price": 189.99,
    "image": productImages['x-ergo'],
    "stores": [],
    "trending": false,
    "isNew": false,
    "releaseDate": "2026-05-01",
    "upcomingRelease": true,
    "description": "The next evolution of the Ergo. Ships May 2026."
  },
  {
    "id": "16",
    "name": "FF2020T Trimmer",
    "brand": "JRL",
    "category": "Trimmers",
    "price": 209.99,
    "image": productImages['ff2020t'],
    "stores": [],
    "trending": false,
    "isNew": false,
    "releaseDate": "2026-06-15",
    "upcomingRelease": true,
    "description": "JRL's upcoming FF2020T trimmer. Pre-order info coming soon."
  },
  {
    "id": "17",
    "name": "Blade Ice",
    "brand": "Andis",
    "category": "Blades",
    "price": 14.99,
    "image": productImages['blade-ice'],
    "stores": [
      {
        "name": "Amazon UK",
        "url": "https://amazon.co.uk/dp/andis-blade-ice",
        "inStock": true,
        "price": 14.99
      },
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/andis-blade-ice",
        "inStock": true,
        "price": 12.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Coolant spray for clipper and trimmer blades. Keep your tools running cool."
  },
  {
    "id": "18",
    "name": "Pro Cape",
    "brand": "BaByliss PRO",
    "category": "Capes & Aprons",
    "price": 39.99,
    "image": productImages['cape'],
    "stores": [
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/babyliss-cape",
        "inStock": true,
        "price": 39.99
      },
      {
        "name": "Coolblades",
        "url": "https://coolblades.co.uk/babyliss-cape",
        "inStock": true,
        "price": 42.99
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "Lightweight pro cape. Hair-resistant fabric, fits any chair."
  },
  {
    "id": "19",
    "name": "JRL x Lamborghini Diamante Kit (Black)",
    "brand": "JRL",
    "category": "Clippers",
    "price": 999,
    "image": productImages['jrl-lamborghini-black'],
    "stores": [
      {
        "name": "JRL Direct",
        "url": "https://jrlusa.com/lamborghini-diamante",
        "inStock": true,
        "price": 999
      },
      {
        "name": "Salons Direct",
        "url": "https://salonsdirect.com/jrl-lamborghini-diamante",
        "inStock": true,
        "price": 949.99
      },
      {
        "name": "Coolblades",
        "url": "https://www.coolblades.co.uk/jrl-x-lamborghini-diamante-clipper-trimmer-kit/",
        "inStock": true,
        "price": 979.99
      },
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/jrl-x-lamborghini-clipper-trimmer-kit-black.html",
        "inStock": true,
        "price": 959
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Limited edition JRL x Lamborghini collaboration. Includes the Diamante clipper and trimmer with a diamond-cut black finish and premium presentation case. Signature drop for the serious collector."
  },
  {
    "id": "20",
    "name": "JRL Onyx Cordless Clipper",
    "brand": "JRL",
    "category": "Clippers",
    "price": 259,
    "image": productImages['jrl-onyx'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/jrl-onyx-professional-cordless-hair-clipper.html",
        "inStock": true,
        "price": 259
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "JRL's matte black Onyx edition cordless clipper. Premium build with the proven Fresh Fade motor."
  },
  {
    "id": "21",
    "name": "Wahl 5-Star Vapor Cordless Clipper",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 179,
    "image": productImages['wahl-vapor'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-5-star-vapor-cordless-clipper.html",
        "inStock": true,
        "price": 179
      }
    ],
    "trending": false,
    "isNew": true,
    "description": "Chrome-finished Wahl 5-Star Vapor with signature cordless power. A head-turner on the barber station."
  },
  {
    "id": "22",
    "name": "Gamma+ Boosted Up Modular Super Torque Clipper",
    "brand": "Gamma+",
    "category": "Clippers",
    "price": 269,
    "image": productImages['gamma-boosted-up'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-boosted-up-modular-super-torque-clipper.html",
        "inStock": true,
        "price": 269
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Gamma+'s flagship Boosted Up — modular design with interchangeable lids and super-torque motor."
  },
  {
    "id": "23",
    "name": "JRL Ghost Clipper Trimmer & Foil Shaver Kit",
    "brand": "JRL",
    "category": "Clippers",
    "price": 599,
    "image": productImages['jrl-ghost-kit'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/jrl-ghost-clipper-trimmer-and-foil-shaver.html",
        "inStock": true,
        "price": 599
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Complete 3-piece JRL Ghost kit — cordless clipper, trimmer and foil shaver in translucent white. Pro kit in a box."
  },
  {
    "id": "24",
    "name": "Wahl Magic Clip Cordless (Black)",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 159,
    "image": productImages['magic-clip-black'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-black-cordless-magic-clip-clipper.html",
        "inStock": true,
        "price": 159
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "The legendary 5-Star Magic Clip in a full black finish. Stagger-tooth blade, cordless freedom."
  },
  {
    "id": "25",
    "name": "JRL Ghost Cordless Clipper",
    "brand": "JRL",
    "category": "Clippers",
    "price": 279,
    "image": productImages['jrl-ghost'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/jrl-ghost-professional-cordless-hair-clipper.html",
        "inStock": true,
        "price": 279
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "JRL Ghost Professional cordless clipper in translucent white. Pro power with a unique aesthetic."
  },
  {
    "id": "26",
    "name": "BaByliss PRO Super Motor Skeleton FX Trimmer",
    "brand": "BaByliss PRO",
    "category": "Trimmers",
    "price": 169,
    "image": productImages['babyliss-super-skeleton'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/babyliss-super-motor-skeleton-trimmer.html",
        "inStock": true,
        "price": 169
      }
    ],
    "trending": false,
    "isNew": true,
    "description": "Super motor upgrade to the Skeleton FX. More torque, more cutting power, same skeleton silhouette."
  },
  {
    "id": "27",
    "name": "Wahl Hi-Viz Trimmer",
    "brand": "Wahl",
    "category": "Trimmers",
    "price": 89,
    "image": productImages['wahl-hi-viz'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-hi-viz-trimmer.html",
        "inStock": true,
        "price": 89
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "High-visibility orange Wahl trimmer. Fun colour, serious precision outlining."
  },
  {
    "id": "28",
    "name": "StyleCraft Pro Brushless Saber Trimmer (Black)",
    "brand": "StyleCraft",
    "category": "Trimmers",
    "price": 179,
    "image": productImages['saber-trimmer-black'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-black.html",
        "inStock": true,
        "price": 179
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Brushless motor Saber trimmer in all-black. Longer battery life and quieter operation than the standard Saber."
  },
  {
    "id": "29",
    "name": "Omni Arcane Clipper",
    "brand": "Omni",
    "category": "Clippers",
    "price": 259,
    "image": productImages['omni-arcane'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/omni-arcane-hair-clipper.html",
        "inStock": true,
        "price": 259
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Omni's Arcane clipper — stealth look with modern cordless performance. Cult favourite among forward-thinking barbers."
  },
  {
    "id": "30",
    "name": "StyleCraft Instinct Clipper",
    "brand": "StyleCraft",
    "category": "Clippers",
    "price": 239,
    "image": productImages['instinct'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-instinct-clipper.html",
        "inStock": true,
        "price": 239
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "StyleCraft Instinct — a next-gen cordless clipper with precision blade and pro-grade runtime."
  },
  {
    "id": "31",
    "name": "Gamma+ Boosted Clipper",
    "brand": "Gamma+",
    "category": "Clippers",
    "price": 219,
    "image": productImages['gamma-boosted'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-boosted-clipper.html",
        "inStock": true,
        "price": 219
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "The original Gamma+ Boosted clipper — super-torque magnetic motor at a barber-friendly price."
  },
  {
    "id": "32",
    "name": "Wahl Senior 2.0 Cordless Clipper",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 219,
    "image": productImages['wahl-senior-2'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-senior-2-0-cordless-clipper.html",
        "inStock": true,
        "price": 219
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "The updated Wahl Senior 2.0 cordless. Stronger motor, longer runtime — the iconic Senior reimagined."
  },
  {
    "id": "33",
    "name": "BaByliss PRO Cordless Super Motor Collection",
    "brand": "BaByliss PRO",
    "category": "Clippers",
    "price": 549,
    "image": productImages['babyliss-super-collection'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/babyliss-pro-cordless-super-motor-collection.html",
        "inStock": true,
        "price": 549
      }
    ],
    "trending": false,
    "isNew": true,
    "description": "The full BaByliss PRO Super Motor collection — clipper, trimmer and skeleton in one premium bundle."
  },
  {
    "id": "34",
    "name": "Gamma+ Boosted Super Torque Motor Trimmer",
    "brand": "Gamma+",
    "category": "Trimmers",
    "price": 179,
    "image": productImages['gamma-boosted-trimmer'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-boosted-super-torque-motor-trimmer.html",
        "inStock": true,
        "price": 179
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "Trimmer sibling to the Boosted clipper. Super-torque motor for effortless detail work."
  },
  {
    "id": "35",
    "name": "Wahl Magic Clip Cordless (Gold)",
    "brand": "Wahl",
    "category": "Clippers",
    "price": 169,
    "image": productImages['magic-clip-gold'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/wahl-gold-cordless-magic-clip.html",
        "inStock": true,
        "price": 169
      }
    ],
    "trending": false,
    "isNew": false,
    "description": "The iconic Magic Clip dressed in gold. Same legendary performance, premium gold finish."
  },
  {
    "id": "36",
    "name": "StyleCraft Saber 2.0 Brushless Clipper (Black)",
    "brand": "StyleCraft",
    "category": "Clippers",
    "price": 239,
    "image": productImages['saber-2-black'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-saber-2-0-brushless-motor-clipper-black.html",
        "inStock": true,
        "price": 239
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "StyleCraft Saber 2.0 — brushless motor clipper in black. The successor to the popular original."
  },
  {
    "id": "37",
    "name": "StyleCraft Pro Brushless Saber Trimmer (White)",
    "brand": "StyleCraft",
    "category": "Trimmers",
    "price": 179,
    "image": productImages['saber-trimmer-white'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-pro-brushless-saber-trimmer-white.html",
        "inStock": true,
        "price": 179
      }
    ],
    "trending": false,
    "isNew": true,
    "description": "Brushless motor Saber trimmer in clean white finish. Matches the Saber 2.0 clipper perfectly."
  },
  {
    "id": "38",
    "name": "BaByliss PRO Boost+ Chameleon Skeleton FX Trimmer",
    "brand": "BaByliss PRO",
    "category": "Trimmers",
    "price": 189,
    "image": productImages['babyliss-chameleon'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/babyliss-pro-boost-chameleon-skeleton-fx-trimmer.html",
        "inStock": true,
        "price": 189
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Boost+ Chameleon edition Skeleton FX. Colour-shift finish on the beloved skeleton trimmer body."
  },
  {
    "id": "39",
    "name": "StyleCraft Pro Metal Edition Instinct Clipper",
    "brand": "StyleCraft",
    "category": "Clippers",
    "price": 279,
    "image": productImages['instinct-metal'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-pro-metal-edition-instinct-clipper.html",
        "inStock": true,
        "price": 279
      }
    ],
    "trending": false,
    "isNew": true,
    "description": "Instinct clipper in full metal body. Weightier feel, premium look, same cordless performance."
  },
  {
    "id": "40",
    "name": "Omni Arcane Anomaly Clipper & Trimmer Combo",
    "brand": "Omni",
    "category": "Clippers",
    "price": 479,
    "image": productImages['omni-anomaly'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/omni-arcane-anomaly-clipper-and-trimmer-combo.html",
        "inStock": true,
        "price": 479
      }
    ],
    "trending": true,
    "isNew": true,
    "description": "Omni's Arcane Anomaly set — matching clipper and trimmer in a presentation box."
  },
  {
    "id": "41",
    "name": "StyleCraft Rebel Clipper",
    "brand": "StyleCraft",
    "category": "Clippers",
    "price": 189,
    "image": productImages['stylecraft-rebel'],
    "stores": [
      {
        "name": "Chris & Sons",
        "url": "https://www.chrisandsons.co.uk/gamma-stylecraft-rebel-clipper.html",
        "inStock": true,
        "price": 189
      }
    ],
    "trending": true,
    "isNew": false,
    "description": "StyleCraft Rebel — a punchy mid-range clipper built for high-volume barbershops."
  }
];
